//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Products
    {
        public long ID { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public string ProductName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> Price { get; set; }
        public string ProductImageUrl { get; set; }
        public string ProductImageName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
